### ISSUE TITLE
An Interesting Bug Report

### ISSUE THREAD

**Issue by Woofer21** [RetroPronghorn/Vault74#3] opened 2020-11-26 04:10 UTC
### OS Version:
Windows 10 home, Version: 2004, OS build: 19041.630
### Browser Version:
Google Chrome 87.0.4280.66 (Official Build) (64-bit)
### Bug:
When a user sends a message the chat will not auto-scroll
### How to reproduce:
Send a message to a user the message will not scroll up 
### What Should Happen:
Message will scroll up instead of not moving
### Extra Information/attachments:
Can't find a fix I tried refreshing, closing the tab won't work either, as well as fully closing chrome and re opening it
### Can Reproduce:
:white_check_mark: Woofer21: Google Chrome 87.0.4280.66 (Official Build) (64-bit), Windows 10 home, Version: 2004, OS build: 19041.630
### Can Not Reproduce:
:x: Bandit/lil dumpling :dumpling:: Google Chrome Version 86.0.4240.198 (Official Build) (64-bit), ChromeOS 86.0.4240.198
:x: lamsick: Google Chrome 87.0.4280.66 (Official Build) (64-bit), Windows 10 OS Version 1909 (Build 18363.1198)

**Comment by RetroPronghorn** [comment] 2020-11-29 07:45
Closing for now, I also cannot reproduce.

**Closed by RetroPronghorn** 2020-11-29 07:45 UTC
